import { getPool, dbGet, dbGetAll, dbRun, closePool } from './db-pool'
import { runMigrationsMysql } from './migrations-mysql'
import { eventBus } from './event-bus'
import { hashPassword } from './password'
import { logger } from './logger'
import { parseMentions as parseMentionTokens } from './mentions'
import { ensureAutoGeneratedCredentials } from './auto-credentials'

const isBuildPhase = process.env.NEXT_PHASE === 'phase-production-build'
const isTestMode = process.env.MISSION_CONTROL_TEST_MODE === '1'

/**
 * Get the MySQL connection pool (alias for getPool for backward compat)
 */
export function getDatabase() {
  return getPool()
}

/**
 * Initialize database schema via MySQL migrations
 */
let webhookListenerInitialized = false
let schemaInitialized = false

async function initializeSchema(): Promise<void> {
  if (schemaInitialized) return
  schemaInitialized = true
  try {
    ensureAutoGeneratedCredentials()
    await runMigrationsMysql()
    await seedAdminUserFromEnv()

    // Initialize webhook event listener (once)
    if (!webhookListenerInitialized) {
      webhookListenerInitialized = true
      import('./webhooks').then(({ initWebhookListener }) => {
        initWebhookListener()
      }).catch(() => {
        // Silent - webhooks are optional
      })

      // Start built-in scheduler for runtime installs only.
      if (!isBuildPhase && !isTestMode) {
        import('./scheduler').then(({ initScheduler }) => {
          initScheduler()
        }).catch(() => {
          // Silent - scheduler is optional
        })
      }
    }

    if (!isBuildPhase) {
      logger.info('Database migrations applied successfully')
    }
  } catch (error) {
    logger.error({ err: error }, 'Failed to apply database migrations')
    throw error
  }
}

// Built-in dev credentials (username and password both "admin").
export const BUILTIN_ADMIN_USERNAME = 'admin'
export const BUILTIN_ADMIN_PASSWORD = 'admin'

export function resolveSeedAuthPassword(env: NodeJS.ProcessEnv = process.env): string | null {
  const b64 = env.AUTH_PASS_B64
  if (b64 && b64.trim().length > 0) {
    const normalized = b64.trim()
    const base64Pattern = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/
    if (!base64Pattern.test(normalized)) {
      logger.warn('AUTH_PASS_B64 is not valid base64; falling back to AUTH_PASS')
      return env.AUTH_PASS || null
    }

    try {
      const decoded = Buffer.from(normalized, 'base64').toString('utf8')
      const canonical = Buffer.from(decoded, 'utf8').toString('base64')
      if (canonical !== normalized) {
        logger.warn('AUTH_PASS_B64 failed base64 verification; falling back to AUTH_PASS')
        return env.AUTH_PASS || null
      }
      if (decoded.length > 0) return decoded
      logger.warn('AUTH_PASS_B64 is set but decoded to an empty value; falling back to AUTH_PASS')
    } catch {
      logger.warn('AUTH_PASS_B64 is not valid base64; falling back to AUTH_PASS')
    }
  }

  return env.AUTH_PASS || null
}

async function ensureBuiltInAdmin(): Promise<void> {
  if (isBuildPhase) return
  if (isTestMode) return

  const existing = await dbGet('SELECT id FROM users WHERE username = ?', [BUILTIN_ADMIN_USERNAME])
  if (!existing) {
    const hash = hashPassword(BUILTIN_ADMIN_PASSWORD)
    await dbRun(
      'INSERT INTO users (username, display_name, password_hash, role, provider, is_approved, workspace_id) VALUES (?, ?, ?, ?, ?, ?, ?)',
      [BUILTIN_ADMIN_USERNAME, 'Admin', hash, 'admin', 'local', 1, 1]
    )
    logger.warn('Built-in admin account created — change password immediately at /settings/users')
  } else {
    logger.info(`Built-in admin account exists: ${BUILTIN_ADMIN_USERNAME}`)
  }
}

async function seedAdminUserFromEnv(): Promise<void> {
  await ensureBuiltInAdmin()
}

/**
 * Close database connection pool
 */
export async function closeDatabase(): Promise<void> {
  await closePool()
}

// Type definitions for database entities
export interface Task {
  id: number;
  title: string;
  description?: string;
  status: 'backlog' | 'inbox' | 'assigned' | 'awaiting_owner' | 'in_progress' | 'review' | 'quality_review' | 'done' | 'failed';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  project_id?: number;
  project_ticket_no?: number;
  project_name?: string;
  project_prefix?: string;
  ticket_ref?: string;
  assigned_to?: string;
  created_by: string;
  created_at: number;
  updated_at: number;
  due_date?: number;
  estimated_hours?: number;
  actual_hours?: number;
  outcome?: 'success' | 'failed' | 'partial' | 'abandoned';
  error_message?: string;
  resolution?: string;
  feedback_rating?: number;
  feedback_notes?: string;
  retry_count?: number;
  completed_at?: number;
  tags?: string; // JSON string
  metadata?: string; // JSON string
}

export interface Agent {
  id: number;
  name: string;
  role: string;
  session_key?: string;
  soul_content?: string;
  status: 'offline' | 'idle' | 'busy' | 'error';
  last_seen?: number;
  last_activity?: string;
  created_at: number;
  updated_at: number;
  config?: string; // JSON string
}

export interface Comment {
  id: number;
  task_id: number;
  author: string;
  content: string;
  created_at: number;
  parent_id?: number;
  mentions?: string; // JSON string
}

export interface Activity {
  id: number;
  type: string;
  entity_type: string;
  entity_id: number;
  actor: string;
  description: string;
  data?: string; // JSON string
  created_at: number;
}

export interface Message {
  id: number;
  conversation_id: string;
  from_agent: string;
  to_agent?: string;
  content: string;
  message_type: string;
  metadata?: string; // JSON string
  read_at?: number;
  created_at: number;
}

export interface Notification {
  id: number;
  recipient: string;
  type: string;
  title: string;
  message: string;
  source_type?: string;
  source_id?: number;
  read_at?: number;
  delivered_at?: number;
  created_at: number;
}

export interface Tenant {
  id: number
  slug: string
  display_name: string
  linux_user: string
  plan_tier: string
  status: 'pending' | 'provisioning' | 'active' | 'suspended' | 'error'
  gateway_home: string
  workspace_root: string
  gateway_port?: number
  dashboard_port?: number
  config?: string
  created_by: string
  owner_gateway?: string
  created_at: number
  updated_at: number
}

export interface Workspace {
  id: number
  slug: string
  name: string
  tenant_id: number
  created_at: number
  updated_at: number
}

export interface ProvisionJob {
  id: number
  tenant_id: number
  job_type: 'bootstrap' | 'update' | 'decommission'
  status: 'queued' | 'approved' | 'running' | 'completed' | 'failed' | 'rejected' | 'cancelled'
  dry_run: 0 | 1
  requested_by: string
  approved_by?: string
  runner_host?: string
  idempotency_key?: string
  request_json?: string
  plan_json?: string
  result_json?: string
  error_text?: string
  started_at?: number
  completed_at?: number
  created_at: number
  updated_at: number
}

export interface ProvisionEvent {
  id: number
  job_id: number
  level: 'info' | 'warn' | 'error'
  step_key?: string
  message: string
  data?: string
  created_at: number
}

/**
 * Returns true when the database has zero users — i.e. first-time setup is needed.
 */
export async function needsFirstTimeSetup(): Promise<boolean> {
  try {
    const row = await dbGet<{ count: number }>('SELECT COUNT(*) as count FROM users')
    return (row?.count ?? 0) === 0
  } catch {
    return false
  }
}

// Database helper functions
export const db_helpers = {
  /**
   * Log an activity to the activity stream
   */
  logActivity: async (
    type: string,
    entity_type: string,
    entity_id: number,
    actor: string,
    description: string,
    data?: any,
    workspaceId: number = 1
  ): Promise<void> => {
    const result = await dbRun(`
      INSERT INTO activities (type, entity_type, entity_id, actor, description, data, workspace_id)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `, [type, entity_type, entity_id, actor, description, data ? JSON.stringify(data) : null, workspaceId])

    const activityPayload = {
      id: result.insertId,
      type,
      entity_type,
      entity_id,
      actor,
      description,
      data: data || null,
      created_at: Math.floor(Date.now() / 1000),
      workspace_id: workspaceId,
    }

    // Broadcast to SSE clients (webhooks listen here too)
    eventBus.broadcast('activity.created', activityPayload)
  },

  /**
   * Create notification for @mentions
   */
  createNotification: async (
    recipient: string,
    type: string,
    title: string,
    message: string,
    source_type?: string,
    source_id?: number,
    workspaceId: number = 1
  ): Promise<{ insertId: number; affectedRows: number }> => {
    const result = await dbRun(`
      INSERT INTO notifications (recipient, type, title, message, source_type, source_id, workspace_id)
      VALUES (?, ?, ?, ?, ?, ?, ?)
    `, [recipient, type, title, message, source_type, source_id, workspaceId])

    const notificationPayload = {
      id: result.insertId,
      recipient,
      type,
      title,
      message,
      source_type: source_type || null,
      source_id: source_id || null,
      created_at: Math.floor(Date.now() / 1000),
      workspace_id: workspaceId,
    }

    // Broadcast to SSE clients (webhooks listen here too)
    eventBus.broadcast('notification.created', notificationPayload)

    return result
  },

  /**
   * Parse @mentions from text
   */
  parseMentions: (text: string): string[] => {
    return parseMentionTokens(text)
  },

  /**
   * Update agent status and last seen
   */
  updateAgentStatus: async (agentName: string, status: Agent['status'], activity?: string, workspaceId: number = 1): Promise<void> => {
    const now = Math.floor(Date.now() / 1000)

    // Get agent ID before update
    const agent = await dbGet<{ id: number }>('SELECT id FROM agents WHERE name = ? AND workspace_id = ?', [agentName, workspaceId])

    await dbRun(`
      UPDATE agents
      SET status = ?, last_seen = ?, last_activity = ?, updated_at = ?
      WHERE name = ? AND workspace_id = ?
    `, [status, now, activity, now, agentName, workspaceId])

    // Broadcast agent status change to SSE clients
    if (agent) {
      eventBus.broadcast('agent.status_changed', {
        id: agent.id,
        name: agentName,
        status,
        last_seen: now,
        last_activity: activity || null,
      })
    }

    // Log the status change
    db_helpers.logActivity('agent_status_change', 'agent', agent?.id || 0, agentName, `Agent status changed to ${status}`, { status, activity }, workspaceId).catch(() => {})
  },

  /**
   * Get recent activities for feed
   */
  getRecentActivities: async (limit: number = 50): Promise<Activity[]> => {
    return dbGetAll<Activity>(`
      SELECT * FROM activities
      ORDER BY created_at DESC
      LIMIT ?
    `, [limit])
  },

  /**
   * Get unread notifications for recipient
   */
  getUnreadNotifications: async (recipient: string, workspaceId: number = 1): Promise<Notification[]> => {
    return dbGetAll<Notification>(`
      SELECT * FROM notifications
      WHERE recipient = ? AND read_at IS NULL AND workspace_id = ?
      ORDER BY created_at DESC
    `, [recipient, workspaceId])
  },

  /**
   * Mark notification as read
   */
  markNotificationRead: async (notificationId: number, workspaceId: number = 1): Promise<void> => {
    await dbRun(`
      UPDATE notifications
      SET read_at = ?
      WHERE id = ? AND workspace_id = ?
    `, [Math.floor(Date.now() / 1000), notificationId, workspaceId])
  },

  /**
   * Ensure an agent is subscribed to a task
   */
  ensureTaskSubscription: async (taskId: number, agentName: string, workspaceId: number = 1): Promise<void> => {
    if (!agentName) return
    await dbRun(`
      INSERT IGNORE INTO task_subscriptions (task_id, agent_name)
      SELECT t.id, ?
      FROM tasks t
      WHERE t.id = ? AND t.workspace_id = ?
    `, [agentName, taskId, workspaceId])
  },

  /**
   * Get subscribers for a task
   */
  getTaskSubscribers: async (taskId: number, workspaceId: number = 1): Promise<string[]> => {
    const rows = await dbGetAll<{ agent_name: string }>(`
      SELECT ts.agent_name
      FROM task_subscriptions ts
      JOIN tasks t ON t.id = ts.task_id
      WHERE ts.task_id = ? AND t.workspace_id = ?
    `, [taskId, workspaceId])
    return rows.map((row) => row.agent_name)
  }
}

/**
 * Log a security/admin audit event
 */
export async function logAuditEvent(event: {
  action: string
  actor: string
  actor_id?: number
  target_type?: string
  target_id?: number
  detail?: any
  ip_address?: string
  user_agent?: string
}): Promise<void> {
  await dbRun(`
    INSERT INTO audit_log (action, actor, actor_id, target_type, target_id, detail, ip_address, user_agent)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
  `, [
    event.action,
    event.actor,
    event.actor_id ?? null,
    event.target_type ?? null,
    event.target_id ?? null,
    event.detail ? JSON.stringify(event.detail) : null,
    event.ip_address ?? null,
    event.user_agent ?? null,
  ])

  // Broadcast audit events (webhooks listen here too)
  const securityEvents = ['login_failed', 'user_created', 'user_deleted', 'password_change']
  if (securityEvents.includes(event.action)) {
    eventBus.broadcast('audit.security', {
      action: event.action,
      actor: event.actor,
      target_type: event.target_type ?? null,
      target_id: event.target_id ?? null,
      timestamp: Math.floor(Date.now() / 1000),
    })
  }
}

export async function appendProvisionEvent(event: {
  job_id: number
  level?: 'info' | 'warn' | 'error'
  step_key?: string
  message: string
  data?: any
}): Promise<void> {
  await dbRun(`
    INSERT INTO provision_events (job_id, level, step_key, message, data)
    VALUES (?, ?, ?, ?, ?)
  `, [
    event.job_id,
    event.level || 'info',
    event.step_key ?? null,
    event.message,
    event.data ? JSON.stringify(event.data) : null
  ])
}

// Initialize database on module load — skip during `next build` to prevent
// build-time vs runtime conflicts.
if (typeof window === 'undefined' && !isBuildPhase) {
  initializeSchema().catch((error) => {
    logger.error({ err: error }, 'Failed to initialize database')
  })
}

// Cleanup on process exit
process.on('exit', () => { closePool().catch(() => {}) })
process.on('SIGINT', () => { closePool().catch(() => {}) })
process.on('SIGTERM', () => { closePool().catch(() => {}) })
