import { describe, it, expect, vi, beforeEach } from 'vitest'

const { mockDbRun, mockDbGetOne, mockBroadcast } = vi.hoisted(() => {
  const mockDbRun = vi.fn(() => Promise.resolve({ insertId: 1, affectedRows: 1 }))
  const mockDbGetOne = vi.fn(() => Promise.resolve({ id: 42 }))
  const mockBroadcast = vi.fn()
  return { mockDbRun, mockDbGetOne, mockBroadcast }
})

vi.mock('@/lib/db-pool', () => ({
  getPool: vi.fn(() => ({
    getConnection: vi.fn(() => Promise.resolve({
      release: vi.fn(),
      execute: vi.fn(() => Promise.resolve([[]])),
    })),
  })),
  dbRun: mockDbRun,
  dbGetOne: mockDbGetOne,
  dbGetAll: vi.fn(() => Promise.resolve([])),
  dbTransaction: vi.fn(),
  closePool: vi.fn(() => Promise.resolve()),
}))

vi.mock('@/lib/migrations', () => ({
  runMigrations: vi.fn(() => Promise.resolve()),
}))

vi.mock('@/lib/password', () => ({
  hashPassword: vi.fn((p: string) => `hashed:${p}`),
  verifyPassword: vi.fn(() => false),
}))

vi.mock('@/lib/logger', () => ({
  logger: { info: vi.fn(), error: vi.fn(), warn: vi.fn(), debug: vi.fn() },
}))

vi.mock('@/lib/event-bus', () => ({
  eventBus: { broadcast: mockBroadcast, on: vi.fn(), emit: vi.fn(), setMaxListeners: vi.fn() },
}))

vi.mock('@/lib/auto-credentials', () => ({
  ensureAutoGeneratedCredentials: vi.fn(),
}))

// Import after mocks
import { db_helpers } from '@/lib/db'

describe('parseMentions', () => {
  it('extracts multiple mentions', () => {
    expect(db_helpers.parseMentions('@alice hello @bob')).toEqual(['alice', 'bob'])
  })

  it('returns empty array when no mentions', () => {
    expect(db_helpers.parseMentions('no mentions here')).toEqual([])
  })

  it('extracts single mention', () => {
    expect(db_helpers.parseMentions('hey @alice')).toEqual(['alice'])
  })

  it('handles @@double — captures word chars after @', () => {
    const result = db_helpers.parseMentions('@@double')
    expect(result).toContain('double')
  })

  it('handles mentions at start and end of string', () => {
    expect(db_helpers.parseMentions('@start and @end')).toEqual(['start', 'end'])
  })

  it('supports hyphen, underscore, and dots in handles', () => {
    expect(db_helpers.parseMentions('ping @agent-code_reviewer.v2 now')).toEqual(['agent-code_reviewer.v2'])
  })

  it('deduplicates repeated mentions case-insensitively', () => {
    expect(db_helpers.parseMentions('@Alice please sync with @alice')).toEqual(['Alice'])
  })

  it('returns empty array for empty string', () => {
    expect(db_helpers.parseMentions('')).toEqual([])
  })
})

describe('logActivity', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockDbRun.mockResolvedValue({ insertId: 1, affectedRows: 1 })
  })

  it('inserts activity into database and broadcasts event', async () => {
    await db_helpers.logActivity('task_created', 'task', 1, 'alice', 'Created task')

    expect(mockDbRun).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO activities'),
      ['task_created', 'task', 1, 'alice', 'Created task', null, 1],
    )
    expect(mockBroadcast).toHaveBeenCalledWith(
      'activity.created',
      expect.objectContaining({
        type: 'task_created',
        entity_type: 'task',
        entity_id: 1,
        actor: 'alice',
      }),
    )
  })

  it('stringifies data when provided', async () => {
    const data = { key: 'value' }
    await db_helpers.logActivity('update', 'agent', 2, 'bob', 'Updated agent', data)

    expect(mockDbRun).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO activities'),
      ['update', 'agent', 2, 'bob', 'Updated agent', JSON.stringify(data), 1],
    )
  })
})

describe('createNotification', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockDbRun.mockResolvedValue({ insertId: 5, affectedRows: 1 })
  })

  it('inserts notification and broadcasts event', async () => {
    await db_helpers.createNotification('alice', 'mention', 'Mentioned', 'You were mentioned')

    expect(mockDbRun).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO notifications'),
      ['alice', 'mention', 'Mentioned', 'You were mentioned', undefined, undefined, 1],
    )
    expect(mockBroadcast).toHaveBeenCalledWith(
      'notification.created',
      expect.objectContaining({
        recipient: 'alice',
        type: 'mention',
        title: 'Mentioned',
      }),
    )
  })

  it('passes source_type and source_id when provided', async () => {
    await db_helpers.createNotification('bob', 'alert', 'Alert', 'CPU high', 'agent', 5)

    expect(mockDbRun).toHaveBeenCalledWith(
      expect.stringContaining('INSERT INTO notifications'),
      ['bob', 'alert', 'Alert', 'CPU high', 'agent', 5, 1],
    )
  })
})

describe('updateAgentStatus', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    mockDbGetOne.mockResolvedValue({ id: 42 })
    mockDbRun.mockResolvedValue({ insertId: 1, affectedRows: 1 })
  })

  it('updates agent status in database and broadcasts', async () => {
    await db_helpers.updateAgentStatus('worker-1', 'busy', 'Processing task')

    expect(mockDbRun).toHaveBeenCalledWith(
      expect.stringContaining('UPDATE agents'),
      expect.arrayContaining(['busy', 'worker-1']),
    )
    expect(mockBroadcast).toHaveBeenCalledWith(
      'agent.status_changed',
      expect.objectContaining({
        id: 42,
        name: 'worker-1',
        status: 'busy',
      }),
    )
  })
})
